### ISSUE TITLE
Add possibility to visualize prometheus histogram data (metrics with bucket suffix)

### ISSUE THREAD

**Issue by LuboVarga** [mtanda/grafana-histogram-panel#23]
Sample data obtained from query **sort(http_response_duration_milliseconds_bucket{job="service",statusCode="201",action="internalEvent"})**:

```
amqp_response_duration_milliseconds_bucket{action="internalEvent",env="test8",instance="app1.gogle.sk:22552",job="service",le="6",statusCode="201"} 67
amqp_response_duration_milliseconds_bucket{action="internalEvent",env="test8",instance="app1.gogle.sk:22552",job="service",le="12",statusCode="201"}    730
amqp_response_duration_milliseconds_bucket{action="internalEvent",env="test8",instance="app1.gogle.sk:22552",job="service",le="24",statusCode="201"}    3895
amqp_response_duration_milliseconds_bucket{action="internalEvent",env="test8",instance="app1.gogle.sk:22552",job="service",le="48",statusCode="201"}    10882
amqp_response_duration_milliseconds_bucket{action="internalEvent",env="test8",instance="app1.gogle.sk:22552",job="service",le="96",statusCode="201"}    18871
amqp_response_duration_milliseconds_bucket{action="internalEvent",env="test8",instance="app1.gogle.sk:22552",job="service",le="1800",statusCode="201"}  29640
amqp_response_duration_milliseconds_bucket{action="internalEvent",env="test8",instance="app1.gogle.sk:22552",job="service",le="2200",statusCode="201"}  29640
amqp_response_duration_milliseconds_bucket{action="internalEvent",env="test8",instance="app1.gogle.sk:22552",job="service",le="+Inf",statusCode="201"}  29640
```

This is native histogram data (support in prometheus libraries, where buckets are created), thus there is just need for visualizing things, not to calculate anything. I have thought that this plugin does visualize data metrics like this and not actually calculate histogram for gauge metrics.

**Comment by mtanda** [comment]
I really want to support this feature.
But, it is difficult to support because Grafana datasource plugin return time series data, not histogram data.

For elasticsearch datasource, there is related issue. https://github.com/grafana/grafana/issues/3164
I'm waiting for Grafana itself support histogram data.

**Comment by LuboVarga** [comment]
I know, but in prometheus there are also only time series data. Histogram data is a bunch of time series data with common labels (only "le" label is not common and it is bucket info, meaning "less than") and metrics name which have suffix "_bucket". Do you have ability in visualization to grab more timeseries and visualize them just as single graph?

I am javascript noob, but it seems to me that this method [getHistogramPairs](https://github.com/mtanda/grafana-histogram-panel/blob/master/src/histogram.js#L154) have all data which is needed to visualize histogram. Only problem I see is that logic calling this method would need to change (one time series  on input does mean one histogram on output).

PS: I can help with coding, but it would require a bit noob help probably.

**Comment by mtanda** [comment]
> but in prometheus there are also only time series data

Yes, it is correct. But datasource plugin can't handle non time series data.

This is a sample result what datasource plugin pass to panel plugin.
(I get the return value at https://github.com/grafana/grafana/blob/v3.1.0/public/app/plugins/datasource/prometheus/datasource.ts#L121)

```
[
  {
    "target" : "go_goroutines{instance=\"localhost:9090\",job=\"prometheus\"}",
    "datapoints" : [
      [
        447,
        1468580585000
      ],
      [
        447,
        1468580595000
      ],
      ...
      [
        443,
        1468580885000
      ]
    ]
  }
]
```

In datasource plugin, metrics name and labels is converted to legend label (by legend format setting), and any other label information is lost.
So, to get the "le" label value, panel plugin need to parse "target" in result.
If you set legend format like "{{instance}} {{le}}" or something, it is impossible to parse it because panel plugin doesn't know legend format.

To support the Prometheus histogram result, Grafana should define standard format like following, and datasource plugin should support it.

```
[
  {
    "target" : "go_goroutines{instance=\"localhost:9090\",job=\"prometheus\"}",
    "histogram" : true,
    "datapoints" : [
      {
        count: 447,
        le: 10
      },
      {
        count: 447,
        le: 20
      },
      ...
      {
        count: 443,
        le: 100
      }
    ]
  }
]
```

**Comment by LuboVarga** [comment]
Thanks for clarification. Now I get it. This have to wait until grafana changes its api to support histograms data.

**Comment by mtanda** [comment]
Thanks for understanding :-)
